### PR TITLE
Can someone check these please.

### PR DESCRIPTION
**Pull request by drvinceknight**
Images appear broken on my machine but fine here... Can someone just make sure I've not made a stupid mistake?

### CODE REVIEW

**Comment by marcharper** [comment]
I checked a few and they llook fine on github to me. Is there one in particular that is off?

**Comment by drvinceknight** [comment]
All the reproduce ones are messed up on my machine... As long as those look fine let's just merge this in :)

We'll need to tell @mojones that he might want to retune the lookeruper :)

**Comment by langner** [comment]
Looks good to me, too.

**Comment by drvinceknight** [comment]
Thanks :)

**Comment by drvinceknight** [comment]
> We'll need to tell @mojones that he might want to retune the lookeruper :)

Scrap that: for some reason I thought it wasn't doing so well... I need to rest...

**Pull request merged**
